// <auto-generated />
using System;
using Backend_ZS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_ZS.API.Migrations
{
    [DbContext(typeof(ZsDbContext))]
    [Migration("20251121181821_map accesscardentrance to accesscard")]
    partial class mapaccesscardentrancetoaccesscard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.BarOrderDetail", b =>
                {
                    b.Property<Guid>("BarOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BarProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("BarOrderId", "BarProductId");

                    b.HasIndex("BarProductId");

                    b.ToTable("BarOrderDetails");
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.BarProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BarProducts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("626e7d51-6573-4b46-b789-36756d9cffb5"),
                            Name = "Lager Beer",
                            Qty = 120,
                            UnitPrice = 3.5
                        },
                        new
                        {
                            Id = new Guid("66274ceb-b662-4f3e-b413-7ebc64426af7"),
                            Name = "Whiskey Shot",
                            Qty = 80,
                            UnitPrice = 5.75
                        },
                        new
                        {
                            Id = new Guid("09df7b74-9cb1-4605-9fc7-5054b109c285"),
                            Name = "Red Wine Glass",
                            Qty = 60,
                            UnitPrice = 6.25
                        },
                        new
                        {
                            Id = new Guid("bd68b7a0-bce6-4159-818a-4bc084ae45fe"),
                            Name = "Margarita",
                            Qty = 45,
                            UnitPrice = 7.5
                        },
                        new
                        {
                            Id = new Guid("8c758180-2375-4b27-bea4-d25e8a657608"),
                            Name = "Gin Tonic",
                            Qty = 70,
                            UnitPrice = 6.0
                        },
                        new
                        {
                            Id = new Guid("ccde323d-2a39-4cd1-96d8-a634d3a87d33"),
                            Name = "Rum & Coke",
                            Qty = 90,
                            UnitPrice = 5.25
                        },
                        new
                        {
                            Id = new Guid("afc8b253-4a00-4e0b-8993-5e74605ca49f"),
                            Name = "Tequila Shot",
                            Qty = 100,
                            UnitPrice = 4.75
                        },
                        new
                        {
                            Id = new Guid("16a4efed-7353-48ed-b046-2532bdc62c74"),
                            Name = "Craft IPA Beer",
                            Qty = 110,
                            UnitPrice = 4.25
                        });
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7248fc3-2585-4efb-8d1d-1c555f4087f6"),
                            Address = "Av. Amazonas N34-120, Quito",
                            Email = "carlos.perez@example.com",
                            Name = "Carlos Pérez",
                            NationalId = "0102030405",
                            Number = "0991234567"
                        },
                        new
                        {
                            Id = new Guid("b68c1f84-4a8c-4ee3-8a6a-4b35a27ad331"),
                            Address = "Calle 10 y Av. 6 de Diciembre, Quito",
                            Email = "maria.gomez@example.com",
                            Name = "María Gómez",
                            NationalId = "1102233445",
                            Number = "0987654321"
                        },
                        new
                        {
                            Id = new Guid("c8b5c2df-4b91-4239-b134-88a3d52f91d8"),
                            Address = "Cdla. Los Ceibos, Guayaquil",
                            Email = "luis.torres@example.com",
                            Name = "Luis Torres",
                            NationalId = "0923456789",
                            Number = "0971122334"
                        },
                        new
                        {
                            Id = new Guid("e6ab1df7-b60b-4db9-96f7-4f6cb5f00219"),
                            Address = "Av. Flavio Alfaro y 13 de Abril, Manta",
                            Email = "ana.morales@example.com",
                            Name = "Ana Morales",
                            NationalId = "1309876543",
                            Number = "0969988776"
                        },
                        new
                        {
                            Id = new Guid("f97b5672-00b9-48c9-85b4-3b897e8af8bb"),
                            Address = "La Mariscal, Av. Colón y Reina Victoria, Quito",
                            Email = "jose.herrera@example.com",
                            Name = "José Herrera",
                            NationalId = "1723345566",
                            Number = "0995566778"
                        },
                        new
                        {
                            Id = new Guid("b02cfb22-4e26-4dd3-8e62-43d29cb86e1e"),
                            Address = "Centro Histórico, Loja",
                            Email = "sofia.ruiz@example.com",
                            Name = "Sofía Ruiz",
                            NationalId = "1803342211",
                            Number = "0954433221"
                        },
                        new
                        {
                            Id = new Guid("3a28b14c-4f9d-4d4c-9021-1894a8b6a2d1"),
                            Address = "Av. de las Américas, Cuenca",
                            Email = "andres.castillo@example.com",
                            Name = "Andrés Castillo",
                            NationalId = "0911223344",
                            Number = "0945566778"
                        },
                        new
                        {
                            Id = new Guid("d5127f6c-6b5b-4b4a-a9e1-2b8d4f508e45"),
                            Address = "Av. Eloy Alfaro y Portugal, Quito",
                            Email = "gabriela.chavez@example.com",
                            Name = "Gabriela Chávez",
                            NationalId = "1204433221",
                            Number = "0983344556"
                        },
                        new
                        {
                            Id = new Guid("1f8a42f5-9e9a-4c1b-bc5a-8d4129fd78c2"),
                            Address = "Cdla. Alborada, Mz. 103, Guayaquil",
                            Email = "ricardo.mendoza@example.com",
                            Name = "Ricardo Mendoza",
                            NationalId = "1005566778",
                            Number = "0978899001"
                        },
                        new
                        {
                            Id = new Guid("e71b9b12-84c3-4c6b-b6e5-5f889b5cf2b7"),
                            Address = "Av. Universitaria, Ambato",
                            Email = "elena.vega@example.com",
                            Name = "Elena Vega",
                            NationalId = "1509988776",
                            Number = "0932211445"
                        });
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.EntranceAccessCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EntranceDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EntranceEntryTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("EntranceExitTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("AccessCardId");

                    b.ToTable("EntranceAccessCards");
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.Key", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("KeyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastAssignedTo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LastAssignedTo");

                    b.ToTable("Keys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("45444a34-3c82-479c-8508-6a2bc2bc62a3"),
                            Available = true,
                            KeyCode = "1H"
                        },
                        new
                        {
                            Id = new Guid("cae24c39-7da2-44da-b7be-541f4d1249e1"),
                            Available = true,
                            KeyCode = "2H"
                        },
                        new
                        {
                            Id = new Guid("8b894d60-ec69-4ce4-8f4c-a356876e6663"),
                            Available = true,
                            KeyCode = "3H"
                        },
                        new
                        {
                            Id = new Guid("30c6f6a7-4f56-4eed-bb46-a8e842f1530e"),
                            Available = true,
                            KeyCode = "4H"
                        },
                        new
                        {
                            Id = new Guid("ee58c343-f78d-4f7c-8666-43f10e7cc3e6"),
                            Available = true,
                            KeyCode = "5H"
                        },
                        new
                        {
                            Id = new Guid("8f39c2ce-900a-4f7a-87f9-185883dcd676"),
                            Available = true,
                            KeyCode = "6H"
                        },
                        new
                        {
                            Id = new Guid("3d0b9380-2ecd-4b59-806b-d3a492b3fd23"),
                            Available = true,
                            KeyCode = "7H"
                        },
                        new
                        {
                            Id = new Guid("c42c5738-e341-4271-837f-fe14027a1629"),
                            Available = true,
                            KeyCode = "8H"
                        },
                        new
                        {
                            Id = new Guid("3f0b2c42-d013-43cc-b9a0-31624540de66"),
                            Available = true,
                            KeyCode = "9H"
                        },
                        new
                        {
                            Id = new Guid("18135631-9634-4394-8e02-edb76898fc33"),
                            Available = true,
                            KeyCode = "10H"
                        },
                        new
                        {
                            Id = new Guid("4f0bf30c-4196-4583-9467-a87ac7b6f7b5"),
                            Available = true,
                            KeyCode = "11H"
                        },
                        new
                        {
                            Id = new Guid("0f0c3028-0ab8-49fb-9ac5-b159180301a3"),
                            Available = true,
                            KeyCode = "12H"
                        },
                        new
                        {
                            Id = new Guid("7e67dc08-3dc4-48fe-914f-056bb32b5708"),
                            Available = true,
                            KeyCode = "13H"
                        },
                        new
                        {
                            Id = new Guid("e4f24e5b-91c5-48f6-92fc-9987ae7944fb"),
                            Available = true,
                            KeyCode = "14H"
                        },
                        new
                        {
                            Id = new Guid("6cfd2ac6-97e4-4655-97f4-f25b59ec02b2"),
                            Available = true,
                            KeyCode = "15H"
                        },
                        new
                        {
                            Id = new Guid("ab87b21d-fcc7-476f-97fa-f7122ffcc7b4"),
                            Available = true,
                            KeyCode = "16H"
                        },
                        new
                        {
                            Id = new Guid("9a2288a1-4efe-41ed-996b-8dbf42f276eb"),
                            Available = true,
                            KeyCode = "1M"
                        },
                        new
                        {
                            Id = new Guid("77325ac7-b5e7-4ef3-85d3-508f35f5a6a3"),
                            Available = true,
                            KeyCode = "2M"
                        },
                        new
                        {
                            Id = new Guid("872ce271-7889-43f5-9026-be8fba6f09e2"),
                            Available = true,
                            KeyCode = "3M"
                        },
                        new
                        {
                            Id = new Guid("e0178342-b601-49f5-aa8b-dc586d6c2bde"),
                            Available = true,
                            KeyCode = "4M"
                        },
                        new
                        {
                            Id = new Guid("413c9a8b-4357-4c46-b763-8858c71acee9"),
                            Available = true,
                            KeyCode = "5M"
                        },
                        new
                        {
                            Id = new Guid("b5cc7d05-0a2a-4e21-8093-a43b6567f764"),
                            Available = true,
                            KeyCode = "6M"
                        },
                        new
                        {
                            Id = new Guid("85c4a0eb-1bf1-4f4b-82be-1866cbd81452"),
                            Available = true,
                            KeyCode = "7M"
                        },
                        new
                        {
                            Id = new Guid("59fa5bbe-058e-491e-bc68-d8447c0ff854"),
                            Available = true,
                            KeyCode = "8M"
                        },
                        new
                        {
                            Id = new Guid("2338b9bd-ee2a-4af3-8c75-00b43598b75d"),
                            Available = true,
                            KeyCode = "9M"
                        },
                        new
                        {
                            Id = new Guid("e2ce6866-d740-4eea-8abc-ebd5ff126f71"),
                            Available = true,
                            KeyCode = "10M"
                        },
                        new
                        {
                            Id = new Guid("c21eb091-27f3-4238-ac95-f3597ac99a6b"),
                            Available = true,
                            KeyCode = "11M"
                        },
                        new
                        {
                            Id = new Guid("4d03a50b-5e50-4348-9b06-9a783413a01b"),
                            Available = true,
                            KeyCode = "12M"
                        },
                        new
                        {
                            Id = new Guid("0e6ec433-ce0b-41eb-b3c8-c3f643bb4c8e"),
                            Available = true,
                            KeyCode = "13M"
                        },
                        new
                        {
                            Id = new Guid("ba54bb28-0887-4583-bd32-26d65b56283f"),
                            Available = true,
                            KeyCode = "14M"
                        },
                        new
                        {
                            Id = new Guid("4d818dc0-7822-4758-98a7-7cf2959e3b00"),
                            Available = true,
                            KeyCode = "15M"
                        },
                        new
                        {
                            Id = new Guid("ddf2eaa4-251e-428e-b1cc-6f65b40af74a"),
                            Available = true,
                            KeyCode = "16M"
                        });
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransactionItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("TransactionItemId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.TransactionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.ToTable("TransactionItems", (string)null);

                    b.HasDiscriminator<string>("TransactionType").HasValue("TransactionItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.AccessCard", b =>
                {
                    b.HasBaseType("Backend_ZS.API.Models.Domain.TransactionItem");

                    b.Property<int>("Uses")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("AccessCard");
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.BarOrder", b =>
                {
                    b.HasBaseType("Backend_ZS.API.Models.Domain.TransactionItem");

                    b.HasDiscriminator().HasValue("BarOrder");
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.EntranceTransaction", b =>
                {
                    b.HasBaseType("Backend_ZS.API.Models.Domain.TransactionItem");

                    b.Property<DateOnly>("EntranceDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EntranceEntryTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("EntranceExitTime")
                        .HasColumnType("time");

                    b.Property<int>("NumberAdults")
                        .HasColumnType("int");

                    b.Property<int>("NumberChildren")
                        .HasColumnType("int");

                    b.Property<int>("NumberDisabled")
                        .HasColumnType("int");

                    b.Property<int>("NumberSeniors")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("EntrancsTransaction");
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.Parking", b =>
                {
                    b.HasBaseType("Backend_ZS.API.Models.Domain.TransactionItem");

                    b.Property<DateOnly>("ParkingDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("ParkingEntryTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("ParkingExitTime")
                        .HasColumnType("time");

                    b.HasDiscriminator().HasValue("Parking");
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.BarOrderDetail", b =>
                {
                    b.HasOne("Backend_ZS.API.Models.Domain.BarOrder", "BarOrder")
                        .WithMany("Details")
                        .HasForeignKey("BarOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_ZS.API.Models.Domain.BarProduct", "BarProduct")
                        .WithMany()
                        .HasForeignKey("BarProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BarOrder");

                    b.Navigation("BarProduct");
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.EntranceAccessCard", b =>
                {
                    b.HasOne("Backend_ZS.API.Models.Domain.AccessCard", "AccessCard")
                        .WithMany()
                        .HasForeignKey("AccessCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessCard");
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.Key", b =>
                {
                    b.HasOne("Backend_ZS.API.Models.Domain.Client", "LastAssignedClient")
                        .WithMany()
                        .HasForeignKey("LastAssignedTo");

                    b.Navigation("LastAssignedClient");
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.Transaction", b =>
                {
                    b.HasOne("Backend_ZS.API.Models.Domain.Client", "Client")
                        .WithMany("Transactions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_ZS.API.Models.Domain.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId");

                    b.HasOne("Backend_ZS.API.Models.Domain.TransactionItem", "TransactionItem")
                        .WithMany()
                        .HasForeignKey("TransactionItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Payment");

                    b.Navigation("TransactionItem");
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.Client", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.BarOrder", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
