// <auto-generated />
using System;
using Backend_ZS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_ZS.API.Migrations
{
    [DbContext(typeof(ZsDbContext))]
    [Migration("20251107151727_Explicit Discriminatory Column TransactionItem")]
    partial class ExplicitDiscriminatoryColumnTransactionItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.BarOrderDetail", b =>
                {
                    b.Property<Guid>("BarOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BarProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BarOrderId", "BarProductId");

                    b.HasIndex("BarProductId");

                    b.ToTable("BarOrderDetails");
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.BarProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BarProducts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("626e7d51-6573-4b46-b789-36756d9cffb5"),
                            Name = "Lager Beer",
                            Qty = 120,
                            UnitPrice = 3.5
                        },
                        new
                        {
                            Id = new Guid("66274ceb-b662-4f3e-b413-7ebc64426af7"),
                            Name = "Whiskey Shot",
                            Qty = 80,
                            UnitPrice = 5.75
                        },
                        new
                        {
                            Id = new Guid("09df7b74-9cb1-4605-9fc7-5054b109c285"),
                            Name = "Red Wine Glass",
                            Qty = 60,
                            UnitPrice = 6.25
                        },
                        new
                        {
                            Id = new Guid("bd68b7a0-bce6-4159-818a-4bc084ae45fe"),
                            Name = "Margarita",
                            Qty = 45,
                            UnitPrice = 7.5
                        },
                        new
                        {
                            Id = new Guid("8c758180-2375-4b27-bea4-d25e8a657608"),
                            Name = "Gin Tonic",
                            Qty = 70,
                            UnitPrice = 6.0
                        },
                        new
                        {
                            Id = new Guid("ccde323d-2a39-4cd1-96d8-a634d3a87d33"),
                            Name = "Rum & Coke",
                            Qty = 90,
                            UnitPrice = 5.25
                        },
                        new
                        {
                            Id = new Guid("afc8b253-4a00-4e0b-8993-5e74605ca49f"),
                            Name = "Tequila Shot",
                            Qty = 100,
                            UnitPrice = 4.75
                        },
                        new
                        {
                            Id = new Guid("16a4efed-7353-48ed-b046-2532bdc62c74"),
                            Name = "Craft IPA Beer",
                            Qty = 110,
                            UnitPrice = 4.25
                        });
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7248fc3-2585-4efb-8d1d-1c555f4087f6"),
                            Address = "Av. Amazonas N34-120, Quito",
                            Email = "carlos.perez@example.com",
                            Name = "Carlos Pérez",
                            NationalId = "0102030405",
                            Number = "0991234567"
                        },
                        new
                        {
                            Id = new Guid("b68c1f84-4a8c-4ee3-8a6a-4b35a27ad331"),
                            Address = "Calle 10 y Av. 6 de Diciembre, Quito",
                            Email = "maria.gomez@example.com",
                            Name = "María Gómez",
                            NationalId = "1102233445",
                            Number = "0987654321"
                        },
                        new
                        {
                            Id = new Guid("c8b5c2df-4b91-4239-b134-88a3d52f91d8"),
                            Address = "Cdla. Los Ceibos, Guayaquil",
                            Email = "luis.torres@example.com",
                            Name = "Luis Torres",
                            NationalId = "0923456789",
                            Number = "0971122334"
                        },
                        new
                        {
                            Id = new Guid("e6ab1df7-b60b-4db9-96f7-4f6cb5f00219"),
                            Address = "Av. Flavio Alfaro y 13 de Abril, Manta",
                            Email = "ana.morales@example.com",
                            Name = "Ana Morales",
                            NationalId = "1309876543",
                            Number = "0969988776"
                        },
                        new
                        {
                            Id = new Guid("f97b5672-00b9-48c9-85b4-3b897e8af8bb"),
                            Address = "La Mariscal, Av. Colón y Reina Victoria, Quito",
                            Email = "jose.herrera@example.com",
                            Name = "José Herrera",
                            NationalId = "1723345566",
                            Number = "0995566778"
                        },
                        new
                        {
                            Id = new Guid("b02cfb22-4e26-4dd3-8e62-43d29cb86e1e"),
                            Address = "Centro Histórico, Loja",
                            Email = "sofia.ruiz@example.com",
                            Name = "Sofía Ruiz",
                            NationalId = "1803342211",
                            Number = "0954433221"
                        },
                        new
                        {
                            Id = new Guid("3a28b14c-4f9d-4d4c-9021-1894a8b6a2d1"),
                            Address = "Av. de las Américas, Cuenca",
                            Email = "andres.castillo@example.com",
                            Name = "Andrés Castillo",
                            NationalId = "0911223344",
                            Number = "0945566778"
                        },
                        new
                        {
                            Id = new Guid("d5127f6c-6b5b-4b4a-a9e1-2b8d4f508e45"),
                            Address = "Av. Eloy Alfaro y Portugal, Quito",
                            Email = "gabriela.chavez@example.com",
                            Name = "Gabriela Chávez",
                            NationalId = "1204433221",
                            Number = "0983344556"
                        },
                        new
                        {
                            Id = new Guid("1f8a42f5-9e9a-4c1b-bc5a-8d4129fd78c2"),
                            Address = "Cdla. Alborada, Mz. 103, Guayaquil",
                            Email = "ricardo.mendoza@example.com",
                            Name = "Ricardo Mendoza",
                            NationalId = "1005566778",
                            Number = "0978899001"
                        },
                        new
                        {
                            Id = new Guid("e71b9b12-84c3-4c6b-b6e5-5f889b5cf2b7"),
                            Address = "Av. Universitaria, Ambato",
                            Email = "elena.vega@example.com",
                            Name = "Elena Vega",
                            NationalId = "1509988776",
                            Number = "0932211445"
                        });
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransactionItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("TransactionItemId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.TransactionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.ToTable("TransactionItems", (string)null);

                    b.HasDiscriminator<string>("TransactionType").HasValue("TransactionItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.BarOrder", b =>
                {
                    b.HasBaseType("Backend_ZS.API.Models.Domain.TransactionItem");

                    b.HasDiscriminator().HasValue("BarOrder");
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.BarOrderDetail", b =>
                {
                    b.HasOne("Backend_ZS.API.Models.Domain.BarOrder", "BarOrder")
                        .WithMany("Details")
                        .HasForeignKey("BarOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_ZS.API.Models.Domain.BarProduct", "BarProduct")
                        .WithMany()
                        .HasForeignKey("BarProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BarOrder");

                    b.Navigation("BarProduct");
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.Transaction", b =>
                {
                    b.HasOne("Backend_ZS.API.Models.Domain.Client", "Client")
                        .WithMany("Transactions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_ZS.API.Models.Domain.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId");

                    b.HasOne("Backend_ZS.API.Models.Domain.TransactionItem", "TransactionItem")
                        .WithMany()
                        .HasForeignKey("TransactionItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Payment");

                    b.Navigation("TransactionItem");
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.Client", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Backend_ZS.API.Models.Domain.BarOrder", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
